"use client";

import { FormEvent, useRef, useState } from "react";
import { Mic, Play, Send, Volume2 } from "lucide-react";
import { api, ChatMessage, LanguageCode } from "@/lib/api";
import { speechLocale } from "@/lib/languages";
import { getRecognitionConstructor, RecognitionLike } from "@/lib/speech";
import { readSavedSession, saveSavedSession } from "@/lib/session";

type VoiceMessage = ChatMessage & { voice?: boolean };

export default function WhatsAppPage() {
  const [sessionId, setSessionId] = useState<string>(); const [language, setLanguage] = useState<LanguageCode>("hi"); const [messages, setMessages] = useState<VoiceMessage[]>([]); const [text, setText] = useState(""); const [listening, setListening] = useState(false); const [starting, setStarting] = useState(false); const [error, setError] = useState(""); const recognition = useRef<RecognitionLike | null>(null);
  const start = async () => { setStarting(true); setError(""); try { const lang = readSavedSession().language; setLanguage(lang); const created = await api.createSession("whatsapp", lang, true); setSessionId(created.session_id); setMessages([{speaker:"agent",text:created.greeting,language:lang,voice:true}]); saveSavedSession({ sessionId: created.session_id, language: lang, profile: created.profile, recommendations: [] }); } catch { setError("Chat could not start. Please try again."); } finally { setStarting(false); } };
  const send = async (value: string, voice = false) => { if (!sessionId || !value.trim()) return; setMessages((all) => [...all,{speaker:"user",text:value.trim(),language,voice}]); setText(""); try { const response = await api.sendMessage(sessionId,value.trim(),language); setMessages((all) => [...all,{speaker:"agent",text:response.agent_text,language:response.response_language,voice:true}]); saveSavedSession({ sessionId, profile:response.profile, language }); } catch (caught) { setError(caught instanceof Error ? caught.message : "Message could not be sent."); } };
  const startVoiceNote = () => { if (!sessionId) { void start(); return; } const Recognition = getRecognitionConstructor(); if (!Recognition) { setError("Browser voice notes are unavailable here. Please use the text box."); return; } const next = new Recognition(); recognition.current = next; next.lang=speechLocale(language); next.interimResults=false; next.continuous=false; next.onstart=()=>setListening(true); next.onend=()=>setListening(false); next.onerror=()=>{setListening(false);setError("Voice note was not understood. Please try again.");}; next.onresult=(event)=> { const transcript = Array.from(event.results).map((result)=>result[0].transcript).join(" "); void send(transcript,true); }; next.start(); };
  const submit = (event: FormEvent) => {event.preventDefault();void send(text);};
  const play = async (message: VoiceMessage) => { try { const response=await api.synthesize(message.text,message.language as LanguageCode || language); if(response.headers.get("content-type")?.includes("audio/")){const url=URL.createObjectURL(await response.blob());const player=new Audio(url);player.onended=()=>URL.revokeObjectURL(url);await player.play();return;} } catch { /* local voice continues below */ } const utterance=new SpeechSynthesisUtterance(message.text);utterance.lang=speechLocale((message.language as LanguageCode)||language);window.speechSynthesis.cancel();window.speechSynthesis.speak(utterance); };
  return <div className="whatsapp-layout"><aside className="whatsapp-info card"><p className="page-eyebrow">WhatsApp voice-note simulation</p><h1>Speak in a chat you already understand.</h1><p>For a real integration, a verified business account and webhook would pass incoming voice notes through the same speech and conversation adapters. This screen demonstrates that inclusive channel without claiming a live WhatsApp connection.</p><div className="notice notice--blue">The green interface is a visual simulation only. No message is sent to WhatsApp from this prototype.</div><div style={{marginTop:18}}><b style={{color:"#003366",fontSize:13}}>How to demonstrate</b><ol style={{color:"#5d6b7d",fontSize:13,lineHeight:1.8,paddingLeft:20}}><li>Start the chat.</li><li>Press the microphone and speak a voice note.</li><li>Play JeevikaSetu&apos;s voice reply.</li><li>Open the profile to show the shared decision engine.</li></ol></div></aside><section className="whatsapp-phone"><div className="whatsapp-head"><div className="wa-avatar">☸</div><div><b>JeevikaSetu</b><span>{sessionId ? "online • voice livelihood guide" : "prototype channel"}</span></div></div><div className="wa-messages">{!sessionId && <div className="wa-bubble">Tap <b>Start chat</b> below to begin a fictional WhatsApp channel demo.</div>}{messages.map((message,index)=><div className={message.speaker === "user" ? "wa-bubble wa-bubble--user" : "wa-bubble"} key={`${message.text}-${index}`}>{message.voice ? <div className="voice-note"><button aria-label="Play voice note" onClick={()=>void play(message)}><Play size={13} fill="currentColor"/></button><div className="line"/><span>0:0{Math.min(9,Math.max(2,Math.ceil(message.text.length/45)))}</span></div> : null}<span style={{display:message.voice?"block":"inline",marginTop:message.voice?6:0}}>{message.text}</span></div>)}</div>{error&&<div style={{background:"#fff0f0",color:"#9c2525",padding:"7px 10px",fontSize:11}}>{error}</div>}{!sessionId ? <div className="wa-composer"><button className="btn btn-green" style={{width:"100%"}} disabled={starting} onClick={()=>void start()}>{starting?"Starting…":"Start chat demo"}</button></div> : <form className="wa-composer" onSubmit={submit}><button type="button" className="wa-mic" onClick={startVoiceNote} aria-label="Record voice note">{listening?<Volume2 size={19}/>:<Mic size={19}/>}</button><input value={text} onChange={(event)=>setText(event.target.value)} placeholder={listening?"Listening…":"Type a message"}/><button className="wa-send" aria-label="Send message"><Send size={18}/></button></form>}</section></div>;
}
